# Generated by Django 4.2.8 on 2024-05-20 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "정기 예금 상품"), (2, "적금 상품"), (3, "연금 저축 상품")]
                    ),
                ),
                ("fin_co_no", models.TextField()),
                ("fin_prdt_cd", models.TextField()),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("join_deny", models.TextField(null=True)),
                ("mtrt_int", models.TextField(null=True)),
                ("max_limit", models.TextField(null=True)),
                ("join_way", models.TextField(null=True)),
                ("spcl_cnd", models.TextField(null=True)),
                ("pnsn_kind_nm", models.TextField(null=True)),
                ("btrm_prft_rate_1", models.FloatField(null=True)),
                ("btrm_prft_rate_2", models.FloatField(null=True)),
                ("btrm_prft_rate_3", models.FloatField(null=True)),
                ("prdt_type_nm", models.TextField(null=True)),
                ("avg_prft_rate", models.FloatField(null=True)),
                (
                    "joined_users",
                    models.ManyToManyField(
                        related_name="join_products", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "like_users",
                    models.ManyToManyField(
                        related_name="like_products", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_6", models.FloatField(null=True)),
                ("month_12", models.FloatField(null=True)),
                ("month_24", models.FloatField(null=True)),
                ("month_36", models.FloatField(null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
