# Generated by Django 4.2.8 on 2024-05-20 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "정기 예금 상품"), (2, "적금 상품"), (3, "연금 저축 상품")]
                    ),
                ),
                ("topFinGrpNo", models.TextField()),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("join_deny", models.TextField()),
                ("mtrt_int", models.TextField(null=True)),
                ("max_limit", models.TextField(null=True)),
                ("join_way", models.TextField(null=True)),
                ("spcl_cnd", models.TextField(null=True)),
                ("pnsn_kind_nm", models.TextField(null=True)),
                ("brtm_prft_rate_1", models.TextField(null=True)),
                ("brtm_prft_rate_2", models.TextField(null=True)),
                ("brtm_prft_rate_3", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JoinedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
