# Generated by Django 4.2.8 on 2024-05-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="이름", max_length=20),
        ),
    ]
